# Generated by Django 4.2.6 on 2023-11-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('organism_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, max_length=56, null=True)),
                ('taxid', models.IntegerField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['group', 'organism_name'],
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('NCBI', 'NCBI'), ('ENSEMBL', 'ENSEMBL'), ('other', 'other')], default='NCBI', max_length=10)),
                ('version', models.CharField(max_length=56)),
                ('ftp_path', models.CharField(blank=True, max_length=512, null=True)),
                ('local_path', models.CharField(blank=True, max_length=1028, null=True)),
                ('metadata', models.CharField(blank=True, max_length=1256, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annot.specie')),
            ],
            options={
                'ordering': ['specie', 'version'],
                'unique_together': {('specie', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aligner', models.CharField(max_length=10)),
                ('fa_path', models.CharField(max_length=256)),
                ('index_path', models.CharField(max_length=256)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='annot.genome')),
            ],
            options={
                'ordering': ['genome', 'aligner'],
                'unique_together': {('genome', 'aligner')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('file_format', models.CharField(blank=True, max_length=8, null=True)),
                ('annot_type', models.CharField(choices=[('DNA', 'DNA'), ('transcript', 'transcript'), ('protein', 'protein'), ('CDS', 'CDS'), ('RNA', 'RNA'), ('other', 'other')], default='other', max_length=24)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annots', to='annot.genome')),
            ],
            options={
                'ordering': ('genome', 'file_path'),
                'unique_together': {('genome', 'file_path')},
            },
        ),
    ]
