# Generated by Django 4.2.6 on 2023-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='fa_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
