# Generated by Django 4.2.6 on 2023-11-08 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('method_name', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1028, null=True)),
            ],
            options={
                'ordering': ['method_name'],
            },
        ),
        migrations.CreateModel(
            name='MethodTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='rna_seq.method')),
            ],
            options={
                'ordering': ['method', 'tool'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='project ID')),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=526)),
                ('status', models.CharField(choices=[('A', 'active'), ('D', 'deleted')], default='A', max_length=1)),
                ('sequencing', models.CharField(choices=[('mrna-seq', 'mRNA-Seq'), ('mirna-seq', 'miRNA-Seq'), ('scrna-seq', 'scRNA-Seq'), ('other', 'other')], default='mrna-seq', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner identified by user_id')),
            ],
            options={
                'ordering': ['project_id', 'owner'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10, verbose_name='Task ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Task Name')),
                ('params', models.CharField(blank=True, max_length=1256, verbose_name='parameters in json string')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('method_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rna_seq.methodtool')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rna_seq.project', verbose_name='Project ID')),
            ],
            options={
                'ordering': ('project', 'task_id'),
                'unique_together': {('project', 'task_id')},
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('tool_path', models.CharField(max_length=256)),
                ('exe_path', models.CharField(max_length=256)),
                ('default_params', models.CharField(blank=True, max_length=1028, null=True, verbose_name='default parameters of the tool')),
            ],
            options={
                'ordering': ['tool_name', 'version'],
                'unique_together': {('tool_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TaskTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_task', to='rna_seq.task')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='rna_seq.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_task', to='rna_seq.task')),
            ],
            options={
                'ordering': ('task',),
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suspend', 'suspend'), ('ready', 'ready'), ('pause', 'pause'), ('run', 'run'), ('finish', 'finish'), ('fail', 'fail')], default='suspend', max_length=10)),
                ('command', models.CharField(max_length=5000, verbose_name='command for tool launching')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='rna_seq.task')),
            ],
            options={
                'ordering': ('task', 'id', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.project', verbose_name='Executed project identified by project_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='executor identified by user_id')),
            ],
            options={
                'ordering': ['project', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=128)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='rna_seq.methodtool')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rna_seq.methodtool')),
            ],
            options={
                'ordering': ['pipeline_name', 'step'],
            },
        ),
        migrations.AddField(
            model_name='methodtool',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='rna_seq.tool'),
        ),
        migrations.CreateModel(
            name='MethodRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rna_seq.method')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.method')),
            ],
            options={
                'ordering': ['method', 'child'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='methodtool',
            unique_together={('method', 'tool')},
        ),
    ]
