# Generated by Django 4.2.6 on 2023-11-08 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rna_seq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=128)),
                ('file_format', models.CharField(blank=True, max_length=10, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parsed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['batch_name', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=50)),
                ('sample_name', models.CharField(max_length=100)),
                ('metadata', models.CharField(blank=True, max_length=3000, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('study_name', 'sample_name'),
            },
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.rawdata')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.sample')),
            ],
            options={
                'ordering': ('sample', 'raw_data'),
            },
        ),
        migrations.CreateModel(
            name='SampleProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_projects', to='rna_seq.project')),
                ('sample_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='rna_seq.samplefile')),
            ],
            options={
                'ordering': ['project', 'sample_file'],
            },
        ),
    ]
