# Generated by Django 4.2.6 on 2023-11-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0002_rawdata_sample_samplefile_sampleproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sequencing',
            field=models.CharField(choices=[('mrna-seq', 'mRNA-Seq'), ('mirna-seq', 'miRNA-Seq'), ('scrna-seq', 'scRNA-Seq'), ('other', 'other')], default='mrna-seq', max_length=10, verbose_name='Sequencing technique'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('ready', 'ready'), ('locked', 'locked'), ('deleted', 'deleted')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='method_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rna_seq.methodtool', verbose_name='Method and Tool'),
        ),
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.CharField(blank=True, max_length=1256, verbose_name='Parameters (in json string format)'),
        ),
    ]
