# Generated by Django 4.2.6 on 2023-11-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rna_seq', '0003_alter_project_project_name_alter_project_sequencing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktree',
            options={'ordering': ('task', 'child')},
        ),
        migrations.RemoveField(
            model_name='tasktree',
            name='parent',
        ),
        migrations.AlterField(
            model_name='tasktree',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='rna_seq.task', verbose_name='Child task'),
        ),
        migrations.AlterField(
            model_name='tasktree',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rna_seq.task', verbose_name='Task'),
        ),
    ]
