# Generated by Django 4.2.6 on 2023-11-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annot', '0002_alter_reference_fa_path'),
        ('rna_seq', '0004_alter_tasktree_options_remove_tasktree_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annot.specie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=526, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project name'),
        ),
    ]
